### ISSUE TITLE
Terraform forces map(any) type for integrations to have the exact same structure

### ISSUE THREAD

**Issue by ferhatys** [terraform-aws-modules/terraform-aws-apigateway-v2#100]
## Description

We're passing a `map(any)` of integrations into the module for setting the API GW integrations. However, Terraform is trying to infer the type of the items inside the map and is enforcing the same structure. So we can't have one integration where we pass a `lambda_arn` and another one where we pass the `integration_uri` without the `lambda_arn` for example. 

## Versions

- Module version 2.2.2:

- Terraform version:
1.6.2
- Provider version(s):

aws 5.37.0

## Reproduction Code [Required]

```
integrations = tomap({
    "POST /xxx" = {
      lambda_arn             = module.lambda[0].lambda_function_arn
      payload_format_version = "2.0"
      timeout_milliseconds   = 12000
      integration_type       = "AWS_PROXY"
    },
    "$default" = {
      connection_type    = "VPC_LINK"
      vpc_link           = "main"
      integration_type   = "HTTP_PROXY"
      integration_method = "ANY"
      authorizer_key     = "xxx"
      authorization_type = "CUSTOM"
      integration_uri = data.aws_lb_listener.backend[0].arn
    }
  })
  ```

## Expected behavior

`terraform plan` is executed successfully.

## Actual behavior

`terraform plan` fails with the following message.

```
│ The given value is not suitable for module.api_gateway.var.integrations
126│ declared at .terraform/modules/api_gateway/variables.tf:197,1-24: attribute
127│ types must all match for conversion to map.
128╵
129Error: Terraform exited with code 1.
130Error: Process completed with exit code 1.
```

**Comment by antonbabenko** [comment]
Just remove `tomap()`, see code in examples/complete directory.
