### ISSUE TITLE
5.0 Update fails to find nested subdomain route53 zones

### ISSUE THREAD

**Issue by plukevdh** [terraform-aws-modules/terraform-aws-apigateway-v2#105]
## Description

When attempting to update from < 5.0 to 5.0, I get new errors relating to route53 hosted zone discovery that did not exist prior to the update. It appears that the code to lookup the hosted zone for the gateway has changed when using the `domain_name` parameter when using single subdomained domains, i.e., 

Zone domain: `my.domain.here.io`
Subdomain/domain of the api gateway: `testing.my.domain.here.io`

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 5.0

- Terraform version: Terraform v1.3.5 or v1.7.4
- Provider version(s):

provider registry.terraform.io/hashicorp/aws v5.52.0

## Reproduction Code [Required]

```terraform
provider "aws" {
  region = "us-east-1"
}

data "aws_region" "current" {}

data "aws_route53_zone" "verify" {
  name = "my.domain.here.io"
}

module "gateway" {
  source  = "terraform-aws-modules/apigateway-v2/aws"
  version = "5.0.0"

  name          = "test-endpoint"
  protocol_type = "HTTP"

  # Custom domain
  domain_name = "testing.my.domain.here.io"

  # Routes and integrations
  routes = {
    "GET /" = {
      integration = {
        uri                    = "arn:aws:lambda:us-east-1:${data.aws_region.current.name}:function:my-function"
        payload_format_version = "2.0"
      }
    }
  }
}
```

## Expected behavior

I should get a successful `terraform plan` back from this specifying a new API gateway creation

## Actual behavior

```
│ Error: no matching Route 53 Hosted Zone found
│
│   with module.gateway.data.aws_route53_zone.this[0],
│   on .terraform/modules/gateway/main.tf line 134, in data "aws_route53_zone" "this":
│  134: data "aws_route53_zone" "this" {
```

### Terminal Output Screenshot(s)

![CleanShot 2024-06-04 at 18 24 18@2x](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/assets/16054/5527a7e6-a999-414e-9511-9fe6e3f07f33)

## Additional context

If one comments out the module, clears the .terraform directories and re-inits/plans, the `aws_route53_zone` data module finds the zone just fine. My assumption is that the use of the `domain_name` var has changed without clear guidance on how to replicate previous behavior. Apologies if this is in the new documentation or migration guide, I couldn't find it.

**Comment by bryantbiggs** [comment]
I think you would have:

```hcl
  ...
  domain_name = "my.domain.here.io"
  subdomains  = ["testing"]
  ...
```

If you plan to route multiple sub-domains to this in the future, you can use:

```hcl
  ...
  domain_name = "*.my.domain.here.io"
  subdomains  = ["testing"]
  ...
```

Ref https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2?tab=readme-ov-file#multiple-subdomains

**Comment by plukevdh** [comment]
That does appear to at least clear the errors. Is that something that can be added to the migration document? It seems a change from previous behavior that may not be clear to others referencing that document rather than the primary readme.

**Comment by plukevdh** [comment]
Looks like this does resolve my errors, so I'll close. It does appear the final output differs pretty significantly due to the resource reorganization under the hood, which I suppose is expected for a major version number change. Appreciate the quick feedback!
