### ISSUE TITLE
Deployment not triggered on changes of body

### ISSUE THREAD

**Issue by schammah** [terraform-aws-modules/terraform-aws-apigateway-v2#109]
## Is your request related to a problem? Please describe.
The module doesn't trigger a deployment when a change is done to `body` for example when using `openapi.yml` spec

## Describe the solution you'd like.
re trigger deployment when a change to that is done i.e.
replace these [lines](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/blob/master/main.tf#L386-L392)
with
```  
triggers = {
    redeployment = sha1(join(",", tolist([
      jsonencode(aws_apigatewayv2_integration.this),
      jsonencode(aws_apigatewayv2_route.this),
      jsonencode(aws_apigatewayv2_route_response.this),
      jsonencode(aws_apigatewayv2_api.this[0].body),
    ])))
  } 
```

*EDIT: Actually tested this solution but it still didnt trigger deployment on a change in openapi spec*

## Additional context
issue was mentioned in several issues on provider 
i.e. [#14445](https://github.com/hashicorp/terraform-provider-aws/issues/14445)

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.1.0 :tada:
