### ISSUE TITLE
Call to function "coalesce" failed

### ISSUE THREAD

**Issue by dang-ng** [terraform-aws-modules/terraform-aws-apigateway-v2#125]
## Description

i got error when trying creating a simple api_gateway below:

- [v] ✋ I have searched the open/closed issues and my issue is not listed.

## Reproduction Code [Required]

```
module "api_gateway" {
  source        = "terraform-aws-modules/apigateway-v2/aws"
  name          = "UserAPI"
  protocol_type = "HTTP"
  routes = {
    "GET /" = {
      integration = {
        uri = "my lambda arn"
      }
    }
  }
}
```

put the code in main.tf, simply run:

terraform init
terraform plan

## Expected behavior

There shouldn't any error

## Actual behavior

Below error shown in terminal:
```
│ Error: Error in function call
│ 
│   on .terraform/modules/api_gateway/main.tf line 137, in data "aws_route53_zone" "this":
│  137:   name = coalesce(var.hosted_zone_name, local.stripped_domain_name)
│     ├────────────────
│     │ while calling coalesce(vals...)
│     │ local.stripped_domain_name is ""
│     │ var.hosted_zone_name is null
│ 
│ Call to function "coalesce" failed: no non-null, non-empty-string arguments.
```

### Terminal Output Screenshot(s)

<img width="684" alt="image" src="https://github.com/user-attachments/assets/60d80bb8-c215-46da-a7e5-769bda5f4721">

## Additional context

I think it relates to this issue here: https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/pull/119

**Comment by codinronan** [comment]
This is a strange error. The module requires the addition of a domain name? What if I don't want to use one?

**Comment by codinronan** [comment]
I see. If you don't want that, you need to add this to the config:

```
  create_domain_name    = false
  create_domain_records = false
```

This skips the relevant config and avoids the error.

Personally I feel those should default to false (or flip if domain is set) but, this is straightforward enough.

**Comment by dang-ng** [comment]
yeah, these should default to false since these fields are optional as stated in the README file. Thanks anyway @codinronan

**Comment by bryantbiggs** [comment]
> yeah, these should default to false since these fields are optional as stated in the README file.

They are optional because a default value has been set, which is `true`
