### ISSUE TITLE
Adding custom domain should not require create_certificate

### ISSUE THREAD

**Issue by mBlomsterberg** [terraform-aws-modules/terraform-aws-apigateway-v2#126]
## Description

At the moment the module defaults to creating a certificate if custom domain is set. This is misleading as a certificate should be an active decision. Making this behavior problematic because it assumes an action (certificate creation) without explicit user intent. Certificates often come with associated costs, configurations, or compliance requirements, so creating them by default can lead to unintended consequences for the user. Instead, the module should require the user to explicitly opt in to certificate creation, ensuring they are aware of and actively choosing this functionality. This change would align the module's behavior with the principle of least surprise and better support user expectations.

## Versions

- Module version [Required]: v5.2.0

## Reproduction Code [Required]

```hcl
create_domain_name          = true
 domain_name                     = "example.com" 
 # create_certificate             = false 
 domain_name_certificate_arn = "arn:aws:acm:eregion:accountcertificate/xxxxxxxxxxxx"

```

### Affected resource: `aws_apigatewayv2_domain_name` 
```hcl

locals {
  create_certificate = local.create_domain_name && var.create_certificate
}

variable "create_certificate" {
  description = "Whether to create a certificate for the domain"
  type        = bool
  default     = true
}
```

**Comment by bryantbiggs** [comment]
Closing since this isn't a module issue - the default behavior is defined in the variables and projected into the docs
