### ISSUE TITLE
  Set disable_execute_api_endpoint to False doesn't Work

### ISSUE THREAD

**Issue by Jiajun8815** [terraform-aws-modules/terraform-aws-apigateway-v2#128]
## Description

Even though I explicitly set the variable **disable_execute_api_endpoint** to false in the *.tf file, the result of terraform plan still is true. 

- [v] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
5.2.1
- Terraform version:
v1.6.6
- Provider version(s):
hashicorp/aws v5.79.0

## Reproduction Code [Required]

1. create aws api gateway resource via the terraform-aws-modules/apigateway-v2/aws module with settings of disable_execute_api_endpoint = false

2. excute terraform plan to see the result

## Expected behavior

the disable_execute_api_endpoint is false in the plan result

## Actual behavior

the disable_execute_api_endpoint is still true in the plan result

### Terminal Output Screenshot(s)

![image](https://github.com/user-attachments/assets/bf0ff5dc-38c2-4fae-b1b9-5104395232e5)

## Additional context

the source code as below
```module "api_gateway" {
  source = "terraform-aws-modules/apigateway-v2/aws"
  version = "5.2.1"
  disable_execute_api_endpoint = false

  name                         = "${var.prefix}-api"
  description                  = "${var.prefix} HTTP API Gateway"
  protocol_type                = "HTTP"

  cors_configuration = {
    allow_methods = ["POST"]
  }

  domain_name = var.domain_name

  stage_access_log_settings = {
    create_log_group            = true
    log_group_retention_in_days = 7
    format = jsonencode({
      context = {
        domainName              = "$context.domainName"
        integrationErrorMessage = "$context.integrationErrorMessage"
        protocol                = "$context.protocol"
        requestId               = "$context.requestId"
        requestTime             = "$context.requestTime"
        responseLength          = "$context.responseLength"
        routeKey                = "$context.routeKey"
        stage                   = "$context.stage"
        status                  = "$context.status"
        error = {
          message      = "$context.error.message"
          responseType = "$context.error.responseType"
        }
        identity = {
          sourceIP = "$context.identity.sourceIp"
        }
        integration = {
          error             = "$context.integration.error"
          integrationStatus = "$context.integration.integrationStatus"
        }
      }
    })
  }

  routes = {
    "POST /register" = {
      integration = {
        uri                    = module.lambda_function["register"].lambda_function_arn
        payload_format_version = "2.0"
        timeout_milliseconds   = 15000
      }
    }

    "POST /" = {
      integration = {
        uri                    = module.lambda_function["verify"].lambda_function_arn
        payload_format_version = "2.0"
        timeout_milliseconds   = 15000
      }
    }
  }

}

**Comment by bryantbiggs** [comment]
we need a minimal reproduction that is deployable in order to troubleshoot

**Comment by Jiajun8815** [comment]
After I check the source code, I got the root cause why it happened. the module will always set the disable_execute_api_endpoint to true when protocol_type is "HTTP" and not explicitly set create_domain_name to false(default is true). Is that reasonable? If so, I suppose that the author of repo can clarify it in the the readme. Otherwise, the default behavior will make people confused.

**Comment by bryantbiggs** [comment]
What's confusing? Is it not setup correctly per the API Gateway documentation?

**Comment by Jiajun8815** [comment]
I just copied the example from [readme](https://registry.terraform.io/modules/terraform-aws-modules/apigateway-v2/aws/latest) and add the disable_execute_api_endpoint  = false settings which doesn't work. I have to look into the source code to find out the reason.

**Comment by bryantbiggs** [comment]
> I have to look into the source code to find out the reason.

Why do you need to look into the source code - do you understand how API Gateway works, do you understand what should happen when using a custom domain on an HTTP API Gateway?

**Comment by Jiajun8815** [comment]
Yes I know it. I know  I made a mistake of those settings in my file. But the two default beheviors of variables usage are conflicting without any restriction or explanation  and it can be applied successfully against user's expectation.  It's just a suggestion to make it more friendly for user. You can forget it if you do not want to. Thanks.

**Comment by bryantbiggs** [comment]
I can't make something more user friendly if users don't understand how the underlying service works. We set up modules to try to prevent footguns and ensure things are configured correctly (where possible), but we can't detail all of those things because we would be repeating the service documentation. If you read the API Gateway service documentation and understand the behavior of the service - you'll understand why you can't set this value to false when using a custom domain

**Comment by Jiajun8815** [comment]
Just curious how do you konw I don't understand how the underlying service works?
> you'll understand why you can't set this value to false when using a custom domain
Actually I can set the value and apply successfully even the configuration is totally wrong(sorry for my bad as I don't understand how the underlying service works). Is that what you mean something friendly? :)

**Comment by bryantbiggs** [comment]
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-disable-default-endpoint.html
