### ISSUE TITLE
Allow creation of more than one custom domain for an api gateway

### ISSUE THREAD

**Issue by eroteme** [terraform-aws-modules/terraform-aws-apigateway-v2#129]
## Is your request related to a new offering from AWS?
No but it is already possible to do this with the base AWS resource and via the AWS API.

## Is your request related to a problem? Please describe.
The problem is a flexibility issue, API gateways can have more than one custom domain associated with it. This module does not allow this directly (other than sub-domains). Creating custom domains outside of this module can cause issues when redefining custom domains at the later stage as the module controls one of  domains directly

## Describe the solution you'd like.
Allow an (optional) list/map of domains to be provided to the module which will create the custom domains and associated certificates if the bool is set to create.

## Describe alternatives you've considered.
Using the base aws resources to define the same resources as this module

**Comment by eroteme** [comment]
Happy to send PR if you think this request will be merged into the project

**Comment by bryantbiggs** [comment]
Isn't this already supported? https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/tree/master?tab=readme-ov-file#multiple-subdomains

**Comment by eroteme** [comment]
> Isn't this already supported? https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/tree/master?tab=readme-ov-file#multiple-subdomains

Sorry, I didn't make my initial post clear. I am talking about different FQDNs not subdomains, for example custom domains of:

thing.example.com
thing.other.com

Both using the same api gw

**Comment by bryantbiggs** [comment]
Ah ok - no I don't think that will be something we will be able to support here

**Comment by eroteme** [comment]
ok, I will migrate away from the module. Thanks for the clarification.
