### ISSUE TITLE
Support for API keys

### ISSUE THREAD

**Issue by mfulgo** [terraform-aws-modules/terraform-aws-apigateway-v2#2]
It looks like there's no built-in way to generate the `aws_apigatewayv2_route` with [`api_key_required`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_route#api_key_required) set to `true`.

I believe the work around would be to create the routes and integrations outside of the module, which reintroduces a bit of the boilerplate that using this module does away with.

**Comment by antonbabenko** [comment]
This module is in the early alpha version (v0.x.x), many things are missing and will be added when time allows it.

Meanwhile, your workaround sounds like a valid solution.

**Comment by svenlito** [comment]
Closing this issue as it's been added [here](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/commit/c31bc3e34759e97d1ae39a3b619f5e3c4aad38ae)
