### ISSUE TITLE
be able to control detailed_metrics_enabled, throttling_burst_limit, throttling_rate_limit

### ISSUE THREAD

**Issue by davidkarlsen** [terraform-aws-modules/terraform-aws-apigateway-v2#30]
## Is your request related to a new offering from AWS?
no

## Is your request related to a problem? Please describe.
missing exposed functionality

## Describe the solution you'd like.
be able to control: detailed_metrics_enabled, throttling_burst_limit, throttling_rate_limit

## Describe alternatives you've considered.
coming from flat resources, want to replace them with this module.

## Additional context
```
   ~ default_route_settings {
          ~ detailed_metrics_enabled = true -> false
          - throttling_burst_limit   = 100 -> null
          - throttling_rate_limit    = 100 -> null
            # (1 unchanged attribute hidden)
        }
        # (1 unchanged block hidden)
```

I actually see code for this https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/blob/5a7f67401c96bf6856fae8867da4492d9ac5af84/main.tf#L67 - but for some reason it's commented out?

it's problematic to not be able to set the limits as they will then be null, and all traffic will get throttled/denied.

**Comment by antonbabenko** [comment]
The main reason why not all features were implemented is that I didn't have a use case for them myself but also there were bugs in Terraform AWS provider.

PR which adds all the remaining arguments into this module is welcome.

Thanks!

**Comment by davidkarlsen** [comment]
Is it ok to upgrade the provider in the same PR?

**Comment by antonbabenko** [comment]
Yes, we can safely use the latest available version and add all currently present features into this module.

Once we have most of them implemented, I will make a new major release of this module and many of the open issues should be closed.

This is the plan. :)

**Comment by davidkarlsen** [comment]
Got it to work w/o touching provider.
