### ISSUE TITLE
connection_id not set for vpc_links

### ISSUE THREAD

**Issue by davidkarlsen** [terraform-aws-modules/terraform-aws-apigateway-v2#31]
## Description

Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.

## ⚠️ Note
yes, this has been done

## Versions
Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.20.0
+ provider registry.terraform.io/hashicorp/aws v3.37.0 - Terraform:

## Reproduction
```
 vpc_links = {
    md-vpc = {
      name               = "md"
      security_group_ids = [module.security-group.this_security_group_id]
      subnet_ids         = var.private_subnet_ids
    }
  }

  integrations = {
    "$default" = {
      description        = "md loadbalancer integration"
      connection_type    = "VPC_LINK"
      integration_uri    = aws_lb_listener.md_lb_listener.arn
      integration_type   = "HTTP_PROXY"
      integration_method = "ANY"
    }
  }
```

### Code Snippet to Reproduce
See above

## Expected behavior
Vpc connection_id should be added

## Actual behavior
added vpcid manually through ui, it will be removed with apply:
```
 # module.apigw.aws_apigatewayv2_integration.this["$default"] will be updated in-place
  ~ resource "aws_apigatewayv2_integration" "this" {
      - connection_id          = "3sgwo6" -> null
        id                     = "zbdvzrq"
        # (10 unchanged attributes hidden)
    }
```

### Terminal Output Screenshot(s)
See above

## Additional context
api gw, integration through internal NLB lb towards vanilla ec2 instances.

**Comment by antonbabenko** [comment]
Try to set `vpc_link` argument in the `integrations` like shown here:
https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/blob/master/examples/vpc-link-http/main.tf#L69

**Comment by davidkarlsen** [comment]
Thanks - that works!
