### ISSUE TITLE
"Pending validation" certificate state after 45 minutes.

### ISSUE THREAD

**Issue by pmargarc** [terraform-aws-modules/terraform-aws-apigateway-v2#33]
## Description

After creating a Route53 hosted zone in order to execute the _complete-http_ example, I executed `terraform apply` and it took 45 minutes to resolve the deployment. And it resolved as an ACM error caused by a "Pending validation" state of a certificate.

## Versions

 - Terraform: V0.14.9

 - Provider(s): /hashicorp/aws v3.37.0

 - Module: V0.16.0

## Reproduction

`terraform init`
Replace local `domain_name` with your hosted zone name
`terraform apply`

### Terminal Output Screenshot(s)

![image](https://user-images.githubusercontent.com/81362161/116079155-c298d300-a697-11eb-9aed-3f46d64a6e19.png)

**Comment by antonbabenko** [comment]
This example works as long as the domain zone is properly configured and reachable by AWS during the validation phase.
