### ISSUE TITLE
Allow using existing domain name to create API mapping

### ISSUE THREAD

**Issue by akuzni2** [terraform-aws-modules/terraform-aws-apigateway-v2#36]
## Is your request related to a new offering from AWS?
No - this is available if writing the resources from scratch

## Is your request related to a problem? Please describe.
Must create new domain name to be able to create API mapping

## Describe the solution you'd like.
This current module doesn't seem to work if you have an existing domain that you'd like to specify additional endpoints on top of it. Example `my-existing-domain.com` and I'd like to create api_v2 resource which adds a /new-endpoint on top of that domain.
I should be able to specify an existing domain name and specify to create a new API mapping on top of that domain name

## Describe alternatives you've considered.
N/A

## Additional context
[This line](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/blob/5e39fc8e0866d1bd90b735bd4f9d5773561d70ba/main.tf#L110) in this module does not currently allow that. It looks like everything must be TRUE (i.e.`var.create_api_domain_name` must be true) to be able to create the API mapping.

**Comment by antonbabenko** [comment]
Thanks for opening this issue! Very good point. This is indeed a missing feature, so PR is welcome.
