### ISSUE TITLE
Allow Module manage existing API Gateway

### ISSUE THREAD

**Issue by fdmsantos** [terraform-aws-modules/terraform-aws-apigateway-v2#39]
## Is your request related to a new offering from AWS?
No.

## Is your request related to a problem? Please describe.
I Would like have the possibility to manage the Routes/Integrations separately from API Gateway Creation.
Example, I have 3 ECS different services, managed in different terraform tfstates. All these 3 ECS services will integrate with the Same API Gateway. So i would like create API Gateway, and in ECS Services reference the API Gateway ID and create the integration. If i want delete one ECS service, the only thing I need to do is terraform destroy in ECS service stack and the API Route/Integration will be removed, but the API Gateway and the other 2 Route/Integrations continues existing. 
Without this, if i want remove an ECS service, i need to do terraform destroy in ECS Service stack and remove the Route/Integration from API Gateway Terraform code run an update in the API Gateway stack.

## Describe the solution you'd like.

Have a new variable api_gw_id. If the create_api_gateway is equal to false, and create_routes_and_integrations is equal true, the module will use  api_gw_id variable to create the route integrations. 

## Describe alternatives you've considered.
N/A

## Additional context
N/A

**If this makes sense for you, i can submit a pull request with this feature.**

**Comment by CumpsD** [comment]
Looking for this as well

**Comment by CumpsD** [comment]
Solved it right now with

```
resource "aws_apigatewayv2_integration" "this" {
  for_each = var.create_routes_and_integrations ? var.integrations : {}

  api_id      = !var.create && var.create_routes_and_integrations ? var.apigateway_id : aws_apigatewayv2_api.this[0].id
```

and similar changes on other places

**Comment by antonbabenko** [comment]
It sounds like a good idea, but maintaining this feature as part of the resource module is a very large amount of work that we don't want to do. Almost all [terraform-aws-modules](https://github.com/terraform-aws-modules) create at least the core resources (API GW, in the case of this module) and attach other resources to it (optionally).

Terraform does not allow us to write really flexible code that will support use-cases like this that we can easily maintain.

**Comment by CumpsD** [comment]
Isn't it just the above change to support it? for the integrations, routes and authorizers + the variable itself

**Comment by antonbabenko** [comment]
Yes, it is a start, but then someone would like to reuse the externally created resources, like domain name (`aws_apigatewayv2_domain_name`) or other resources. The code will have to grow rather quickly.

**Comment by CumpsD** [comment]
Ok, I'll just update my local copy each time ;)
