### ISSUE TITLE
Support for PrivateLink to NLB for Fargate

### ISSUE THREAD

**Issue by leeming** [terraform-aws-modules/terraform-aws-apigateway-v2#4]
I'm currently learning API gateway and fargate and was just trying to figure out how to get this module to work with it. 

It looks like `connection_id` is required for `aws_apigatewayv2_integration`, which is currently missing in the module definition. Is this right? Is this something you had foreseen, or am I working on an edge case here?

Usually I would take this as an opportunity to submit a PR, but I am still a little early with my understanding of the terraform required.

Thanks, and keep up the great work!

**Comment by antonbabenko** [comment]
Yes, this is right. Currently, there is only functionality which we use at [Betajob](https://www.betajob.com) and we will add new features as we have customers asking for this.

**Comment by antonbabenko** [comment]
Hi @leeming !

[v0.13.0](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/releases/v0.13.0) has been just released, and `connection_id` is supported.

Also, please take a look at [vpc-link-http example](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/tree/master/examples/vpc-link-http) where I show integration of API Gateway with ALB.
