### ISSUE TITLE
After throttling for API Gateway $default stage has been configured, removing throttling_burst_limit and throttling_rate_limit  under  default_route_settings causes API Gateway to set Burst limit=Rate limit=0, which means that all traffic is forbidden, while it should disable any throttling instead

### ISSUE THREAD

**Issue by askaribragimov** [terraform-aws-modules/terraform-aws-apigateway-v2#45]
## Description

The module can take a parameter that specifies throttling for the $default stage:
```
module "api_gateway" {
  source  = "terraform-aws-modules/apigateway-v2/aws"
....
  default_route_settings = {
    throttling_rate_limit  = 100
    throttling_burst_limit = 100
  }
}
```

After a Throttling for $default stage for an API Gateway has been enabled and set to some values, removing `default_route_settings` parameter leads to terraform plan like

      ~ default_route_settings {
          - throttling_burst_limit   = 100 -> null
          - throttling_rate_limit    = 100 -> null 
        }

and this ends up in setting both limits to zero, **disabling traffic completely** (which lead to a service downtime! ):
![image](https://user-images.githubusercontent.com/16650181/126637919-67205372-1a52-4389-8605-c06777924d9d.png)

Instead, we should get 
![image](https://user-images.githubusercontent.com/16650181/126637985-3e362ab1-d762-486f-a15f-170031a8e2ac.png)

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform: Terraform v1.0.0

 - Provider(s):
 ```
+ provider registry.terraform.io/cyrilgdn/postgresql v1.13.0
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.2

```

 - Module: "0.16.0", also manifests with latest-to-date  "1.1.0"

## Reproduction

* Deploy a new API gateway with $default stage _without throttling parameters in `default_route_settings`_. Just do not use this section.
* Proceed to API GW Console to "Throttling->Stage (select $default) ->Throttling for $default stage" and confirm that for API Gw in question Default route throttling values are "Not configured"
* Set in Console Throttling for $default stage as some numbers, e.g. Burst limit =100 and  Rate limit = 100. 
* Still without `default_route_settings` set in Terraform, deploy again. You will get plan like
```
      ~ default_route_settings {
          - throttling_burst_limit   = 100 -> null
          - throttling_rate_limit    = 100 -> null 
        }
```
* Check again API GW Console -> Throttling for $default stage. You will see that Burst limit =0 and  Rate limit = 0. These mean that no traffic is allowed via Gateway and deploying such configuration will cause a break in a service. 

## Expected behavior
After some throttling is already configured as described above, removal of `throttling_burst_limit` and `throttling_rate_limit parameters` inside `default_route_settings` should lead to disabling throttling, that is "Throttling->Stage (select $default) ->Throttling for $default stage" should contain "not configured" again and traffic should not be throttled.

## Actual behavior

After some throttling is already configured as described above, removal of `throttling_burst_limit` and `throttling_rate_limit parameters` inside `default_route_settings` causes these parameters to be set to zero, blocking traffic via gateway completely. 

## Additional context

I have found similar case with original AWS provider but they say it is fixed in an earlier version of the provider. 

https://github.com/hashicorp/terraform-provider-aws/issues/5690

**Comment by bryantbiggs** [comment]
unfortunately this is an issue with the AWS API and there isn't anything we can do here in the module https://github.com/hashicorp/terraform-provider-aws/issues/14742
