### ISSUE TITLE
Support to pass `ignore_changes` attributes as input variables

### ISSUE THREAD

**Issue by gcavalcante8808** [terraform-aws-modules/terraform-aws-apigateway-v2#49]
## Is your request related to a new offering from AWS?
No.

## Is your request related to a problem? Please describe.
Not per see, just a behavior I think.

## Describe the solution you'd like.
We'd like to be able to create API-gateways with terraform but allow our devs to update the integrations using OpenAPI specs.

For that, if we can pass the list of changes to be ignored, like the `integrations` field it will work flawlessly.

## Describe alternatives you've considered.
Bring the `openapi.yaml` spec into the repo workflow and use it for the `body` input value.

**Comment by antonbabenko** [comment]
Terraform does not support configurations variables inside of `ignore_changes`, so can't make it configurable in the module.

There is not much we can do in the module, unfortunately.
