### ISSUE TITLE
Private HTTP API

### ISSUE THREAD

**Issue by vaddiszno** [terraform-aws-modules/terraform-aws-apigateway-v2#6]
Hi Anton,

First of all amazing project thanks for creating it.
I am trying to create a private API with Terraform, using this module.
What would be the process for that? This example?
https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/blob/master/examples/vpc-link-http/main.tf

Thanks,
G

**Comment by antonbabenko** [comment]
Hi @vaddiszno !

I have just pushed another set of features related to the integration of API Gateway with VPC Links in #25, and updated the example `vpc-link-http` that shows it in action.

Now you can create a private HTTP gateway and have integrations with VPC resources.

[v0.12.0](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/releases/v0.12.0) has been just released.


PS: We are still on version 0.xxx of the module, so there may be some breaking changes as we develop new features.
