### ISSUE TITLE
How to specify stage name?

### ISSUE THREAD

**Issue by dobeerman** [terraform-aws-modules/terraform-aws-apigateway-v2#65]
I'm terrible sorry, but I couldn't find a way to specify a stage name. 
Does anyone can show me an example? :thinking: 

Thanks!

**Comment by antonbabenko** [comment]
Only `$default` stage is created by this module.

**Comment by dobeerman** [comment]
@antonbabenko yes, I saw it is commented out. :disappointed: 
Do you have any plans to make it work?

**Comment by antonbabenko** [comment]
I have no plans for that at the moment.
