### ISSUE TITLE
Add integration & route objects to outputs

### ISSUE THREAD

**Issue by rafaljanicki** [terraform-aws-modules/terraform-aws-apigateway-v2#77]
## Is your request related to a problem? Please describe.
I'd like to create a deployment that's being triggered on the integration's or/and route's changes

It's important to return whole objects as IDs wouldn't change on modifications, so we need to run the jsonencode on the whole integrations/routes

**Comment by rafaljanicki** [comment]
Don't stale

**Comment by antonbabenko** [comment]
Please propose a PR with the changes you want to have in the outputs.
