### ISSUE TITLE
Feature: Separate module or Support for REST API/API gateway V1 

### ISSUE THREAD

**Issue by RubberDuckDestroyer** [terraform-aws-modules/terraform-aws-apigateway-v2#79]
Hi there,

I wanted to know if there are any plans to support AWS API Gateway V1/ API Gateway for REST APIs. 
The main factor why I have to use V1 APIs is for using API Keys which isnt supported on API Gatway V2 (HTTP/Websocket APIs). You can find more information on this in the links section at the bottom of this post.

Currently, I've built one API GW (REST) with the team manually using terraform resources. Would be really keen on getting a module for this. I'll be happy to contribute towards building this module if there's any plans for this.

Please let me know if this is something you're interested in / have plans for implementing

Cheers,
Hit.

**Links:**

Terraform resource link: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_rest_api

AWS API Gateway Difference between REST API and HTTP API:  https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html#http-api-vs-rest.differences.management

**Comment by antonbabenko** [comment]
Hi @RubberDuckDestroyer !

Thanks for opening this feature request.

We have no plans to develop a module for API Gateway v1, but we can consider doing it if a company or two want to sponsor its development. This is how some of the Terraform AWS modules were developed in the past.

If you want to continue this discussion, please book some time, and I can explain the details - https://calendly.com/antonbabenko/letstalk
