### ISSUE TITLE
Create lambda integrations from a list

### ISSUE THREAD

**Issue by lashawnta-pf** [terraform-aws-modules/terraform-aws-apigateway-v2#81]
## Is your request related to a new offering from AWS?
  - Yes ✅:  Able to do this if I create resources outside of the module

## Is your request related to a problem? Please describe.
- We are trying to prototype managing the updates to our lambdas outside of terraform and "genericize" the infrastructure as much as we can.  We have a list that has some meta data about the lambda and would like to dynamically create the integration keys based on the list instead of hardcoding.  We also refer to this list when creating the actual lambda resource infrastructure.  So in short, it would be easier to manage if the api-gateway integration and the lambda are reading from the same source list.

## Describe the solution you'd like.
A way to leverage a list to create the integration map entries.

## Describe alternatives you've considered.
- A way to support dynamic/foreach to allow creation of these map entries (not sure if it's supported by terraform)
- recreating the relevant resources outside of the module to leverage the resource support of foreach

## Additional context
Please feel free to provide feedback especially in the case that this is not a good idea.

**Comment by antonbabenko** [comment]
Hi @lashawnta-pf !

I think it is a good idea to be able to manage multiple integrations dynamically.

The easiest way to do this is like you described in "alternatives" - using for loop to create a map of `integrations` passed into this module [here](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/blob/master/examples/complete-http/main.tf#L63-L140).

```hcl
module "api_gateway" {
  source = "terraform-aws-modules/apigateway-v2/aws"

  integrations = { for k, v in {"ANY /" => "my-lambda1", "POST /new" => "my-lambda2"}:

    k = {
      lambda_arn             = v
      payload_format_version = "2.0"
      timeout_milliseconds   = 12000
    }
  }
}
```

Another approach can be to generate YAML/JSON OpenAPI spec file and pass it [like this](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/blob/master/examples/complete-http/main.tf#L142-L144).

These solutions will work great when Lambda functions can be created in advance. If you want to manage Lambdas at the same, you may need to add `depends_on` on modules.

I don't know what else we can do in this module to make this support better than it is now.

**Comment by lashawnta-pf** [comment]
@antonbabenko Thank you so much for your fast response.   I was hoping this would be possible.  This issue can be closed.
