### ISSUE TITLE
Stepfunction Integration Permission not working

### ISSUE THREAD

**Issue by tbehlauProgress** [terraform-aws-modules/terraform-aws-apigateway-v2#87]
## Description

Post to the start-stepfunction endpoint results in a permission error 

## Versions

- Module version [Required]:

- Terraform version: v1.3.5

- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v4.51.0
+ provider registry.terraform.io/hashicorp/external v2.2.3
+ provider registry.terraform.io/hashicorp/local v2.3.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tls v4.0.4

## Reproduction Code [Required]

Run the installation of the complete-http example.
Run `curl -X POST {domain}/start-step-function -d {}`

## Expected behavior

Success message

## Actual behavior

Failed error {"message":"Internal Server Error"}

### Cloudwatch Output 

104.129.198.74 - - [24/Jan/2023:17:52:06 +0000] "POST POST /start-step-function HTTP/1.1" 500 35 fQke_hDCDoEEMpw= API Gateway doesn’t have permissions to assume the IAM role configured on the integration. Check the permissions and try again.

**Comment by antonbabenko** [comment]
Please fill in the issue template to increase the chances of receiving an answer.

Verify that your API Gateway has required permissions, as the error message suggests.
