### ISSUE TITLE
passthrough_behavior error in Terraform 0.14

### ISSUE THREAD

**Issue by michaelkemp** [terraform-aws-modules/terraform-aws-apigateway-v2#9]
Produces "Error: expected passthrough_behavior to be one of [WHEN_NO_MATCH NEVER WHEN_NO_TEMPLATES], got..." when planned with terraform 0.14
Currently no way to set the passthrough_behavior as an input.

**Comment by antonbabenko** [comment]
@michaelkemp FYI [v0.13.0](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/releases/v0.13.0) has been just released.
