### ISSUE TITLE
Be able to create routes separately from integrations

### ISSUE THREAD

**Issue by obi-juan1971** [terraform-aws-modules/terraform-aws-apigateway-v2#90]
## Is your request related to a problem? Please describe.

With this code, when you create an integration, only one route is created.

## Describe the solution you'd like.

It would be very usefull to be able to define routes separately so you may re-use the same integration when needed, for instance: with a VPC Load Balancer integration.

## Describe alternatives you've considered.

A solutions may be similar to the one you use in terraform-aws-modules/alb/aws to create different rules for one listener.

**Comment by klubi** [comment]
Would be great to have this done. I have 20+ routes that could easily reuse single integration... instead I have 20+ of both...
