### ISSUE TITLE
an input for additional stages

### ISSUE THREAD

**Issue by flavono123** [terraform-aws-modules/terraform-aws-apigateway-v2#94]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

5.16.2

## Is your request related to a problem? Please describe.

cannot add more stage by module inputs

## Describe the solution you'd like.

an input like:
```hcl
additional_stages = [
  "dev",
  "prod"
]
```

## Describe alternatives you've considered.

maybe have to use `resource` 😩 
```hcl
module "aws_apigateway_v2" { ... }

resource "aws_apigatewayv2_stage" "example" {
  api_id = module.aws_apigatewayv2_api.this.id
  name   = "dev"
}

resource "aws_apigatewayv2_stage" "example" {
  api_id = module.aws_apigatewayv2_api.this.id
  name   = "dev"
}
```

**Comment by bryantbiggs** [comment]
I'm not sure how applicable this is in a module. you typically deploy to `dev` first and later promote to `prod`, which means that `dev` stage does not always equal `prod`. therefore, I think its better to have to module definitions, one for `dev` and one for `prod` and you can control them independently to promote changes as needed. but I am open to hear thoughts, feedback

**Comment by flavono123** [comment]
![image](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/assets/20619567/d333c2ec-b771-4716-8c9e-8fe0e4dea593)
i can add some stages when i create new one in the web console, [following a workshop](https://catalog.us-east-1.prod.workshops.aws/workshops/4923c0ff-6470-46e1-9884-7c6ee63e7136/ko-KR/simple-api-service/create-apigw). that makes me suggest like this.
i've got what you mean but isn't it make sense?

**Comment by flavono123** [comment]
back to my "real" problem, what i want to do with the module, is solved by resources like:
```hcl
## API Gateway

### API
resource "aws_apigatewayv2_api" "delivery_api" {
  name          = local.apigateway.api_name
  protocol_type = "HTTP"
}


### Deploy/Stages
resource "aws_apigatewayv2_stage" "default" {
  api_id      = aws_apigatewayv2_api.delivery_api.id
  name        = "$default"
  auto_deploy = true
}
resource "aws_apigatewayv2_stage" "dev" {
  api_id      = aws_apigatewayv2_api.delivery_api.id
  name        = local.apigateway.stage_name
  auto_deploy = true
}
```

> I'm not sure how applicable this is in a module.

is it hard to set args(or fix the module configs) for creating above resources only?
or it is not the purpose of this module?
